spring:
  application:
    name: consul-test-app
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true #enables/disables the usage of service discovery
        register: true # enables/disables the registration of this app into Consul as a service
