keycloak:
  auth-server-url: "http://127.0.0.1:8180/auth"
  realm: "area51"
  resource: "login-app"
  public-client: true
  enabled: true
  principal-attribute: "preferred_username"
  security-constraints:
    - authRoles:
        - user
      securityCollections:
        - patterns:
            - "/secured/*"
